// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from 'next/dynamic'

export const components = {
  hero: dynamic(() => import('./Hero')),
  image: dynamic(() => import('./Image')),
  navigation_item: dynamic(() => import('./NavigationItem')),
  rich_text: dynamic(() => import('./RichText')),
}
